= Introducción al aprendizaje
Carlos J. Aragón-Ayala

== Resumen de Estrategia efectiva de aprendizaje

Los pasos interrelacionados y de necessaria alineación son:

. Producir objetivos educacionales: enfocados a la competencia esperada final y relevante, ajustados según circunstancias, incluyendo subyacentes
.. A priori: basándote de recomendaciones o interes personales
... Buscar estándares educacionales internacionales, silabus, curriculos, planes de estudio
... Buscar materiales dependientes de nivel de conociminetos (principiantes, intermedios, avanzados)
.. A posteriori: si tienes un material en frente
... Estructurar específicamente el material de aprendizaje: Requiere lectura "veloz" del material (skipping)
... Reconocer limitaciones de conocimiento previo sobre material:   
. Producir evaluaciones de objetivos educacionales, analizar necesidad de subyacentes
. Usar estrategias de aprendizaje dependiendo del tipo de conocimiento, previa verificación de criterios de uso

== Explicación de la Estrategia efectiva de aprendizaje

== Anexo 1: Tipos de conocimiento

. Terminología
. Detalles y elementos específicos

. Categorías y clasificaciones
. Principios y generalizaciones
. Teorías, modelos y estructuras

. Habilidades y algoritmos específicos del área
. Técnicas y métodos específicos del área
. Criterios para determinar cuando usar el procedimiento

. Estrategias de aprendizaje
. Procesos cognitivos
. Autoconocimiento

== Anexo 2: Procesos de conocimiento

. Reconocer: 
. Evocar

. Interpretar
. Ejemplificar
. Clasificar
. Resumir
. Inferir
. Comparar
. Explicar

. Ejecutar
. Implementar

. Diferenciar
. Organizar
. Atribuir

. Verificar
. Criticar

. Generar
. Planificar
. Producir

