= Objectives

. Enunciar la definición/misión de anestesiología
. Enunciar los riesgos anestesiológicos
. Enunciar indicadores que se monitorizan por el anestesiología
. Enunciar actividad de los anestesio: quirófano, extraquirófano.
. ASA
. evaluacion preanestésica
. Distinguir cuándo usar cada tipo de anestesia.
. ESTA ES UNA PRUEBA DE FUNCIONAMIENTO





== Notas

anestesio, correcto medio para proc qx, analgesia, reanimación.
extraquirófano: tranquilizar, niños, retardo, radioterapia, 

quirófano: reconocer infraestructura y cómo actuar en ella. 
no solo es el cuartito. 
3 zonas: negra, gris, blanca
negra: cambiarse ropa cochina a la limpia y botas (no estéril)
administrativos, cercano a familiares paciente, 
gris: se guardan las cosas al casillero, y se pone la demás ropa,
almacenes de cosas qx-anestesio, medicamentos, zna recup posanestesio
blanca:
zona estratégica, cercano a banco-sangre, uci, ucin, lejos de 
contaminados.

evaluando relajantes musculares

qué se hace si se pincha a la aa. carótida

