= Personal Management
Carlos J. Arag칩n-Ayala <cjaragonayala@gmail.com>

. To develop a personal system to achieve any objective, and integrate all these objectives in an effective and efficient manner.

Bueno, la idea es plantear preguntas y tratar de responderlas, como si de un objetivo se tratase:

. C칩mo puede representarse el pensamiento humano? Que permita plasmarlo y luego repasarlo en forma m치s eficiente que una separaci칩n en "cards".

== Mission

The purpose of your life. 
What is your reason to live?

To have well-being

Well-being::
a person feeling and thinking his or her life is desirable regardless of how others see it.

== The strategy

=== Vision

A long term (~ 10 years) future state you want to be in that evidences the fulfillment of your mission.

To fulfill well-being you can work on the following life domains:

. Health (physical, mental)
. Resources (money, things)
. Social (family, friendship, love)
. Reputation (academical, social)
. Knowledge (all levels)
. Fun (videogames, youtube)
. Goals (dreams, conscious desires)
. Philanthrophy 

To work on these domains you can evaluate your current life in each of them.
Usually a slogan (motivational, short, inspirational).
 
=== Long-term objectives

Short term (~ 5 years) aims. 
Focus on the gap between your current asessment and vision.
To understand how to contribute to erasing these gaps. 

=== Short-term objectives

Operational (~ 1 year) aims.
Realistic (small is best than more and more).
Integral (linked to vission and long-term objectives).
Razonable (justify why these aims are important and not anothers one).

== The tactic 

All (departments/individuals)need SMART actions.
Optimize the actions through review by specialists (feedback).
Actions (departamental/individual) need to be aligned with the strategy.
Horizontal coordination across departments.
Assign responsabilites (direct & supporting)
Integral alignment review (SPADES Matrix)
Define control mechanisms (standarized measurement in graphical view)
Automatic measures (balance, not to overwhelm)
Not to punish when the plan is not fulfilled (identify the root cause and offers help)

== Review the progress

Define a frequency.
Adjust the frequency based on situation (normal, problems, etc)
Use main metrics (other metrics are just operational and not for interest in high level, except when trying to obtain information about problems root causes)
Simple and standard mechanism of report/review
Metrics self-diagnosticable by "workers" (trusty environment)
PDCA (plan-do-check-act): Call for action when something is founded.
Problems as opportunities to enhance itself :v.
THERE ARE NOT BAD PEOPLE, JUST BAD PROCESSES (NOT TO PUNISH).
Open to new ideas or situation (mantein the plan/tactic flexible)
Less formal than monitorizing plan (tactic)

== Refining the strategy
